### PR TITLE
Fix klfda in vignette

### PR DESCRIPTION
**Pull request by terrytangyuan**

### CODE REVIEW

**Comment by sinhrks** [comment]
We shouldn't include example only work on github package, as it should fail on CRAN.

**Comment by terrytangyuan** [comment]
Sure, I was thinking update lfda on CRAN but I'll wait until then.

**Comment by sinhrks** [comment]
OK. I'm going to re-submit ggfortify by beggining of Dec (for ggplot2 fix). 

Is your resubmission meets the schedule? Then I'll wait:)

**Comment by terrytangyuan** [comment]
Maybe not. Please feel free to submit ggfortify on your schedule.

**Pull request closed without merging**
