### PR TITLE
Added coveralls

### PR DESCRIPTION
**Pull request by terrytangyuan**

### CODE REVIEW

**Comment by terrytangyuan** [comment]
@sinhrks I think the error is caused from previous failed build.

**Comment by terrytangyuan** [comment]
Do you mind if I follow this format https://github.com/terrytangyuan/lfda/blob/master/.travis.yml to try to fix the Travis build? I just think the structure/organization of dependencies is much clearer since they can be seperated by Github packages and CRAN packages.

**Comment by sinhrks** [comment]
Thanks for the PR!

Ah, I didn't know the ``apt_packages`` / ``r_binary_packages`` can be used for binary package download. I appreciate it if you will change it.

Currently I followed ``r-travis`` format to download binay packages, but not stick to it.

**Comment by terrytangyuan** [comment]
Ok! I'll try to fix it then!

**Comment by sinhrks** [comment]
I've added you as a contributor:) lmk if you don't want.

Pls push once travis has been passed.

**Comment by terrytangyuan** [comment]
Sure. Thanks!

**Comment by terrytangyuan** [comment]
@sinhrks It's all fixed now!

**Comment by sinhrks** [comment]
Thanks for this:) I'll do some work to increase coverage.

**Comment by sinhrks** [comment]
Hmm, Travis test time gets about 2 times longer... Any thoughts? I'm not particular about it, but it's great if you know a workaround!

**Comment by terrytangyuan** [comment]
Yeah I think I know where the bottleneck is. I'll try to fix it soon.

**Comment by terrytangyuan** [comment]
@sinhrks For some reason, I wasn't able to speed up Travis further. :-( I guess it's due to the addition of installing `covr` library, running `coverall`, and communicating with `coveralls.io`.

**Comment by sinhrks** [comment]
Ok, thanks to confirm.

**Pull request merged**
