### PR TITLE
First try attempt at fortify & autoplot for spline basis objects

### PR DESCRIPTION
**Pull request by DarwinAwardWinner**
My attempt at #128. Unfortunately, I can't test it myself because the package fails `devtools::check()` with a nonsensical error message. It says:

```
Installation failed.
See ‘/private/var/folders/d3/ff25_6td3sjc02d8rfbwvmxc0000gn/T/RtmpxbR4VD/ggfortify.Rcheck/00install.out’ for details.
```

And when I check the suggested log file, I see:

```
* installing *source* package ‘ggfortify’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Warning: namespace ‘IRanges’ is not available and has been replaced
by .GlobalEnv when processing object ‘’
Warning in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘IRanges’
Error in .requirePackage(package) :
  unable to find required package ‘IRanges’
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/private/var/folders/d3/ff25_6td3sjc02d8rfbwvmxc0000gn/T/RtmpxbR4VD/ggfortify.Rcheck/ggfortify’
```

I can't figure out why it's trying to load IRanges, and I can't figure out why it would be unable to do so, since I have it installed.

### CODE REVIEW

**Comment by terrytangyuan** [comment]
Can you try devtools::install_local()? Perhaps it's something weird in check. Try add tibble to Travis install script and test it Travis?

**Comment by terrytangyuan** [comment]
Please also add some tests.

**Comment by DarwinAwardWinner** [comment]
Ok, I added tests, and the Travis build with PKG=STD was successful. The PKG=DEV build seems to run into an error while installing an unrelated dependency.

**Comment by terrytangyuan** [comment]
That's normal. @sinhrks is working on fixing it. Thanks for your contribution! It would be nice to add some vignettes later, like others.

**Comment by terrytangyuan** [comment]
Actually I don't think we want to maintain the DEV build. For example, the following is happening whe n installing `zoo`:
```
Installation failed: 'rcmd_safe_env' is not an exported object from 'namespace:callr
```
What do you think? @sinhrks Should we just disable that build?

**Pull request merged**
