### PR TITLE
Adding new contributors to AUTHORS

### PR DESCRIPTION
**Pull request by terrytangyuan**
Thanks for your contribution! Keep it up and make this package better and better! 
@DarwinAwardWinner @lselzer @DarioS @austin3dickey 

cc: @sinhrks

### CODE REVIEW

**Comment by DarioS** [comment]
My name is Dario Strbenac.

**Comment by terrytangyuan** [comment]
Thanks @DarioS! Also I forgot to include @Rekyt. Thanks all!

**Comment by terrytangyuan** [comment]
@sinhrks Could you take a look and approve this if it looks okay? Thanks!

**Comment by sinhrks** [comment]
LGTM! Appreciate your contributions!

**Pull request merged**
