### PR TITLE
REL: v0.1.0

### PR DESCRIPTION
**Pull request by sinhrks**

### CODE REVIEW

**Comment by sinhrks** [comment]
v0.1.0 has been uploaded to CRAN. 

- https://cran.r-project.org/web/packages/available_packages_by_date.html

- [ ] Merge latest release (from my home PC) including brief notes.
- [ ] Change News and DESCRIPTION version after merge.

**Comment by terrytangyuan** [comment]
How come it can be uploaded even though those check results failed? BTW, the vignettes all have the same name even thought the links are correct.

**Comment by sinhrks** [comment]
The tests are temporary disabled on CRAN using ``skip_on_cran``. We should have use correct  ``VignetteIndexEntry`` for vignettes link texts (being fixed in next release).

The current travis failure is caused by version conflict. Merging and bump version in separate PR.

**Comment by terrytangyuan** [comment]
Yeah I saw those now.

**Pull request merged**
