### PR TITLE
COMPAT: Support ggplot2 1.1.0

### LINKED ISSUE #67: ggfortify installation fails: could not find function "eval"
In both ``install.packages`` and ``install_github``.

```
Error in eval(expr, envir, enclos) : could not find function "eval"
Error : unable to load R code in package ‘ggfortify’
ERROR: lazy loading failed for package ‘ggfortify’
```

Maybe related to ``ggplto2`` dev version: 

- https://github.com/jrnold/ggthemes/issues/36
- https://github.com/dkahle/ggmap/issues/65

### PR DESCRIPTION
**Pull request by sinhrks**
Closes #67. Some changes are required for ggplot2 1.1.0 (dev). This works on my local with ggplot2 dev, still needs followings.

- [x] Add a logic to distinguish ggplot2 version (and use previous logic for earlier vers...).
- [x] Allow Travis to test 1.1.0 and earlier ggplot2 versions 
- ~~R CMD check with R dev version~~ Using R dev version is little hard to maintain dep packages. Skipped.

### CODE REVIEW

**Comment by sinhrks** [comment]
@terrytangyuan Do you know how to make Travis build matrix as below?

1. Standard R / ggplot2
2. R dev / ggplot2 dev (from github)

**Comment by terrytangyuan** [comment]
Try add ```username/reponame@commitHashOrReleaseTagHere``` to `r_github_packages` in the Travis file.

**Comment by sinhrks** [comment]
Thanks, I meant to run 2 builds on Travis (1 is from CRAN, and the other is from GitHub).

Currently it can't in easy way, maybe I have to write a sh to do this...

**Comment by terrytangyuan** [comment]
Oh...Yeah I have never done that before either. Looks like we actually need to write a sh and assign different env like what has done in `pandas` build.

**Comment by terrytangyuan** [comment]
Awesome! Good work!

**Comment by sinhrks** [comment]
Had some troubles on Travis:)

**Pull request merged**
