### PR TITLE
Keep order of factor levels.

### LINKED ISSUE #142: Order of Groups is Undesirably Rearranged
I have a survival grouping where the factor levels are different to alphabetical ordering.

	levels(samplesGroups)
	[1] "Low"  "High"

`survfit` keeps these in the correct order

	> survivalFit
	Call: survfit(formula = survivalData ~ samplesGroups)

		            n events median 0.95LCL 0.95UCL
	samplesGroups=Low  17     11   3.63   1.838      NA
	samplesGroups=High 17     10   4.55   0.992      NA

However, `autoplot` always places High first and Low second in the legend, because it ignores the ordering and just rearranges everything alphabetically. This should not happen.

### LINKED ISSUE #143: Variable Name in Survival Plot Legends
By default, `autoplot` uses the names from `survivalFit[["strata"]]` as the legend levels. They have a `variableName=value` format. Programmer's variable names are not something that a figure to be published in a medical journal should have displayed. Perhaps `autoplot` should use code like `gsub(".*=", '', strataNames)` to place only the level name in the legend. `autoplot` also lacks any legend customisation options, such as the legend title.

### PR DESCRIPTION
**Pull request by DarioS**
survfit from the survival package keeps the user's order of factor levels, but they become alphabetically reordered once ggfortify is used. This change keeps the levels in their original order.

closes #142. closes #143.

### CODE REVIEW

**Comment by terrytangyuan** [comment]
Thank you! Looks like tests failed. You can click to see details. It might also be good to have a test to check whether the order is fixed.

**Comment by sinhrks** [comment]
Thx for the PR! Is this fix both #142 and #143?

**Comment by DarioS** [comment]
Yes, both of them.

**Comment by terrytangyuan** [comment]
@DarioS You can reproduce the lint errors by running this [test_lint.R](https://github.com/sinhrks/ggfortify/blob/master/tests/testthat/test_lint.R)

**Comment by terrytangyuan** [comment]
Thank you! Sorry the lintr thing was annoying.

**Pull request merged**
