### PR TITLE
REL: v0.2.0

### PR DESCRIPTION
**Pull request by sinhrks**
Do not merge until I fix some indications from CRAN.

### CODE REVIEW

**Comment by terrytangyuan** [comment]
Ok sorry :-)

**Comment by sinhrks** [comment]
NP:) I should have write a note.

**Comment by terrytangyuan** [comment]
I sent you an email :-) In case you don't check it often

**Comment by terrytangyuan** [comment]
We can remove Chinese intro if needed. I'll include a link somewhere later instead of keeping it in vignette

**Comment by sinhrks** [comment]
I think it's OK to disable some codes in Chinese doc. Strangely, CRAN reports an error which ldfa is not found. As Travis failure is unrelated to the package, going to re-submit tonight.

**Comment by sinhrks** [comment]
Sorry to take long. Uploaded on CRAN.

https://cran.r-project.org/web/packages/ggfortify/index.html

**Comment by yutannihilation** [comment]
Welcome back! :+1:

**Pull request merged**
